@baseUrl = http://localhost:3000/account

###
# LOGIN
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "Vanvu151105@gmail.com",
    "password": "123456"
}

###
# REGISTER
POST {{baseUrl}}/register
Content-Type: application/json

{
    "fullName": "Test User",
    "email": "luyentuvung+1@gmail.com",
    "password": "123456",
    "address": "HCM",
    "captcha": "test",
    "role": 1
}

###
# SEND OTP
POST {{baseUrl}}/send-otp
Content-Type: application/json

{
    "email": "Vanvu151105@gmail.com",
    "otp": "123456"
}

###
# VERIFY OTP
POST {{baseUrl}}/verify-otp
Content-Type: application/json

{
  "email": "newuser@example.com",
  "otp": "123456"
}

###
# UPDATE PROFILE (address, full name)
PUT {{baseUrl}}/profile/15
Content-Type: application/json

{
  "address": "400 đường Hiệp Thành 13, phường Hiệp Thành",
  "full_name": "Trần Đăng Tùng"
}

### UPDATE PASSWORD
PUT {{baseUrl}}/change-password/15
Content-Type: application/json

{
  "old_password": "123",
  "new_password": "1234567"
}

###
# GET RATING
GET {{baseUrl}}/rating/13

###
# GET PROFILE
GET {{baseUrl}}/profile


###
# GET WIN PRODUCTS
GET {{baseUrl}}/win/19


###
# ADD WATCHLIST
POST {{baseUrl}}/watchlist
Content-Type: application/json


{
  "productId": 1
}

###
# DELETE WATCHLIST
DELETE {{baseUrl}}/watchlist
Content-Type: application/json


{
  "productId": 1
}

###
# GET WATCHLIST
GET {{baseUrl}}/watchlist/15


### -------------------------
# USER REQUEST SELL UPGRADE
### -------------------------
PUT {{baseUrl}}/requestSell/15



### -------------------------
# ADMIN APPROVE REQUEST SELL (ADMIN)
### -------------------------
PUT {{baseUrl}}/approve/14



### -------------------------
# ADMIN DENY REQUEST SELL (ADMIN)
### -------------------------
PUT {{baseUrl}}/deny/14



### -------------------------
# DELETE ACCOUNT (ADMIN)
### -------------------------
DELETE {{baseUrl}}/18



### -------------------------
# GET ALL USERS (ADMIN)
### -------------------------
GET {{baseUrl}}/all

### ADD USER
POST http://localhost:3000/account/add
Content-Type: application/json

{
  "email": "testuser@gmail.com",
  "password": "123456",
  "role": 3,
  "address": "Ho Chi Minh City",
  "full_name": "vu"
}

### UPDATE USER
PUT http://localhost:3000/account/update/13
Content-Type: application/json

{
  "email": "Vanvu151105@gmail.com",
  "address": "Ha Noi",
  "full_name": "Trần Thị B"
}

### =========================
### GET WATCHLIST STATE
### =========================
GET http://localhost:3000/account/watchlist/15/18
Content-Type: application/json


### =========================
### ADD WATCHLIST
### =========================
POST http://localhost:3000/account/watchlist/add
Content-Type: application/json

{
  "user_id": 14,
  "product_id": 10
}


### =========================
### REMOVE WATCHLIST
### =========================
DELETE http://localhost:3000/account/watchlist/remove
Content-Type: application/json

{
  "user_id": 14,
  "product_id": 10
}


### =========================
### AUTH
### =========================
GET http://localhost:3000/auth/me

### =========================
### RATING SCORE
### =========================
GET http://localhost:3000/account/ratingScore/15

### Reset password user (no auth)
PUT  http://localhost:3000/account/reset-password
Content-Type: application/json

{
  "email": "vvvu23@clc.fitus.edu.vn",
  "new_password": "123456"
}
