@baseUrl = http://localhost:3000/bidding


###
### 1. Get bidding list (auth required)
GET {{baseUrl}}/14

###
### 2. Refuse bidder (seller action)
PUT {{baseUrl}}/refuse
Content-Type: application/json

{
    "productId": 1,
    "bidderId": 22
}


###
### 3. Check if user can bid (auth required)
POST {{baseUrl}}/checkCanBid/15
Content-Type: application/json

{
    "product_id": 18
}


###
### 4. Place a new bid (auth required)
POST {{baseUrl}}/bid/15
Content-Type: application/json

{
    "product_id": 20,
    "price": 210000
}


###
### 5. Get bid history for a product
GET {{baseUrl}}/bid_history/1


###
### 6. Deny bidder from a product (auth)
POST {{baseUrl}}/denyBidder/3
Content-Type: application/json

{
    "bidderId": 15
}

###
### 7. Get list of denied bidders (auth)
GET {{baseUrl}}/denyBidder/1


###
### 8. Get fun
GET {{baseUrl}}/fun

### 9. Rate bidder (auth)
POST {{baseUrl}}/rateBidder
Content-Type: application/json

{
    "bidder_id": 14,
    "product_id": 11,
    "rating": 1,
    "comment": "Great bidder!"
}




