@baseUrl = http://localhost:3000/category
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE5IiwiYWRkcmVzcyI6IkhDTSIsInJvbGUiOiIxIiwiZnVsbF9uYW1lIjoiVGVzdCBVc2VyIiwiZW1haWwiOiJsdXllbnR1dnVuZysxQGdtYWlsLmNvbSIsImlhdCI6MTc2NTM1MzY0NSwiZXhwIjoxNzY1MzU3MjQ1fQ.-gI7U_2ac-kV_ezxhz4S-XKZDGG5p_Wd5dxizS0tKbk

### Add new category
POST {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "description": "New Category"
}

### Update category
PUT {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 5,
    "description": "Điện thoại"
}

### Delete category
DELETE {{baseUrl}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 13
}

### Get all categories
GET {{baseUrl}}/all

### Get child categories
GET {{baseUrl}}/child/2

### Get all parent categories
GET {{baseUrl}}/allParent
