@baseUrl = http://localhost:3000/contact
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEzIiwiYWRkcmVzcyI6Ik5ndXllbiBWYW4gUXVhIiwicm9sZSI6IjIiLCJmdWxsX25hbWUiOiJWdSBWdSIsImVtYWlsIjoiVmFudnUxNTExMDVAZ21haWwuY29tIiwiaWF0IjoxNzY0OTE5MDY1LCJleHAiOjE3NjQ5MjI2NjV9.LVsdtyqOFTkA1SzewuAnnKSA7TB-VvJUWFKXxW_muRM

### Ask question
POST {{baseUrl}}/ask
Content-Type: application/json

{
    "product_id": 1,
    "question": "Is this product still available?"
}

### Answer question
PUT {{baseUrl}}/answer
Content-Type: application/json

{
    "productId": 1,
    "questionId": 105,
    "answer": "Yes, it is still available!"
}
